DROP TABLE IF EXISTS flows;

CREATE TABLE flows (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ts TEXT NOT NULL,
  te TEXT NOT NULL,
  ismc TEXT NOT NULL,
  odmc TEXT NOT NULL,
  sa TEXT NOT NULL,
  da TEXT NOT NULL,
  pr TEXT NOT NULL,
  iflg TEXT NOT NULL,
  sp INTEGER NOT NULL,
  dp INTEGER NOT NULL,
  td INTEGER NOT NULL,
  ipkt INTEGER NOT NULL,
  ibyt INTEGER NOT NULL,
  bps INTEGER NOT NULL,
  bpp INTEGER NOT NULL,
  pps INTEGER NOT NULL,
  flw INTEGER NOT NULL,
  lbl INTEGER NOT NULL
);
