"""empty message

Revision ID: a77a7d4a67f7
Revises: 
Create Date: 2019-08-11 15:42:14.370050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77a7d4a67f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifier_name'), 'classifier', ['name'], unique=False)
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=50), nullable=False),
    sa.Column('window', sa.Integer(), nullable=False),
    sa.Column('aggregation', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('split', sa.Integer(), nullable=False),
    sa.Column('kfolds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_file'), 'dataset', ['file'], unique=False)
    op.create_table('feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_name'), 'feature', ['name'], unique=False)
    op.create_table('preprocessing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preprocessing_name'), 'preprocessing', ['name'], unique=False)
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=100), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('classifier_id', sa.Integer(), nullable=False),
    sa.Column('preprocessing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classifier_id'], ['classifier.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['preprocessing_id'], ['preprocessing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_datetime'), 'model', ['datetime'], unique=False)
    op.create_index(op.f('ix_model_file'), 'model', ['file'], unique=False)
    op.create_table('features',
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.PrimaryKeyConstraint('feature_id', 'model_id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_date', sa.DateTime(), nullable=False),
    sa.Column('test_date', sa.DateTime(), nullable=False),
    sa.Column('train_duration', sa.Float(), nullable=False),
    sa.Column('test_duration', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('f1_score', sa.Float(), nullable=False),
    sa.Column('true_negative', sa.Integer(), nullable=False),
    sa.Column('false_positive', sa.Integer(), nullable=False),
    sa.Column('false_negative', sa.Integer(), nullable=False),
    sa.Column('true_positive', sa.Integer(), nullable=False),
    sa.Column('hyperparameters', sa.Text(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('features')
    op.drop_index(op.f('ix_model_file'), table_name='model')
    op.drop_index(op.f('ix_model_datetime'), table_name='model')
    op.drop_table('model')
    op.drop_index(op.f('ix_preprocessing_name'), table_name='preprocessing')
    op.drop_table('preprocessing')
    op.drop_index(op.f('ix_feature_name'), table_name='feature')
    op.drop_table('feature')
    op.drop_index(op.f('ix_dataset_file'), table_name='dataset')
    op.drop_table('dataset')
    op.drop_index(op.f('ix_classifier_name'), table_name='classifier')
    op.drop_table('classifier')
    # ### end Alembic commands ###
